export {
  ALPHA_EQUIVALENCE_TOLERANCE,
  DEFAULT_ALPHA_VALUES,
  FWO_SLOPE_COEFFICIENT,
  GAS_CONSTANT_J_PER_MOL_K,
  STARINK_SLOPE_COEFFICIENT,
  STARINK_TEMPERATURE_EXPONENT,
} from "./constants";
export { analyzeActivationEnergy } from "./analyze";
export { evaluateAnalysisEligibility } from "./eligibility";
export { heatingRateKey } from "./heatingRates";
export {
  calculateFriedman,
  calculateFWO,
  calculateKAS,
  calculateKissinger,
  calculateStarink,
} from "./methods";
export {
  convertHeatingRateToKPerMinute,
  convertTemperatureToKelvin,
  estimateAlphaDerivative,
  estimateFiniteDifference,
  interpolateDerivativeAtAlpha,
  interpolateTemperatureAtAlpha,
  isAmbiguousAlphaCrossing,
  normalizeMassToAlpha,
  prepareThermalRun,
  prepareThermalRuns,
} from "./preprocessing";
export {
  InsufficientRegressionSpreadError,
  MINIMUM_RELATIVE_X_RMS_SPREAD,
  ordinaryLeastSquares,
  studentTCritical95,
} from "./regression";
export type {
  ActivationEnergyAnalysis,
  AlphaActivationEnergyEstimate,
  AlphaMethodResult,
  AnalysisOptions,
  CalculationStatus,
  DerivativeSource,
  Diagnostic,
  DiagnosticCode,
  DiagnosticSeverity,
  EligibilityResult,
  HeatingRateUnit,
  IsoConversionalMethod,
  KissingerPeak,
  KissingerPeakQuality,
  KissingerPeakSourceSignal,
  KissingerResult,
  MassNormalizationOptions,
  MassReference,
  MethodCalculationOptions,
  MethodName,
  MethodObservation,
  PreparationResult,
  PreparedPoint,
  PreparedRun,
  RegressionResult,
  RegressionInputAggregation,
  RegressionInputGroup,
  RunPreparationResult,
  TemperatureUnit,
  ThermalPoint,
  ThermalRun,
  TimeUnit,
} from "./types";
